# Funding - Sponsor this project
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [divyamohan1993]
# ko_fi: divyamohan
# patreon: divyamohan
# custom: ['https://example.com/donate', 'https://example.com/sponsor']
