name: 📚 Documentation Issue
description: Report an issue or suggest improvements for documentation
title: "[Docs]: "
labels: ["documentation"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our documentation! Clear documentation helps farmers and developers alike.

  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect information
        - Unclear explanation
        - Outdated content
        - Typo/Grammar
        - Broken link
        - Translation issue
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is this documentation issue located?
      placeholder: "e.g., README.md, docs/installation.md, or URL"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the documentation issue or improvement.
      placeholder: What's wrong or could be improved?
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How do you think the documentation should be changed?
      placeholder: Your suggestion for improvement...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
