
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const CatalogStatus = {
  DRAFT: 'DRAFT',
  BROADCASTED: 'BROADCASTED',
  SOLD: 'SOLD'
} as const

export type CatalogStatus = (typeof CatalogStatus)[keyof typeof CatalogStatus]


export const NetworkLogType = {
  OUTGOING_CATALOG: 'OUTGOING_CATALOG',
  INCOMING_BID: 'INCOMING_BID'
} as const

export type NetworkLogType = (typeof NetworkLogType)[keyof typeof NetworkLogType]
