
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Farmer` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Farmer
 * 
 */
export type FarmerModel = runtime.Types.Result.DefaultSelection<Prisma.$FarmerPayload>

export type AggregateFarmer = {
  _count: FarmerCountAggregateOutputType | null
  _min: FarmerMinAggregateOutputType | null
  _max: FarmerMaxAggregateOutputType | null
}

export type FarmerMinAggregateOutputType = {
  id: string | null
  name: string | null
  locationLatLong: string | null
  languagePref: string | null
  upiId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FarmerMaxAggregateOutputType = {
  id: string | null
  name: string | null
  locationLatLong: string | null
  languagePref: string | null
  upiId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FarmerCountAggregateOutputType = {
  id: number
  name: number
  locationLatLong: number
  languagePref: number
  upiId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type FarmerMinAggregateInputType = {
  id?: true
  name?: true
  locationLatLong?: true
  languagePref?: true
  upiId?: true
  createdAt?: true
  updatedAt?: true
}

export type FarmerMaxAggregateInputType = {
  id?: true
  name?: true
  locationLatLong?: true
  languagePref?: true
  upiId?: true
  createdAt?: true
  updatedAt?: true
}

export type FarmerCountAggregateInputType = {
  id?: true
  name?: true
  locationLatLong?: true
  languagePref?: true
  upiId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type FarmerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Farmer to aggregate.
   */
  where?: Prisma.FarmerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Farmers to fetch.
   */
  orderBy?: Prisma.FarmerOrderByWithRelationInput | Prisma.FarmerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FarmerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Farmers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Farmers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Farmers
  **/
  _count?: true | FarmerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FarmerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FarmerMaxAggregateInputType
}

export type GetFarmerAggregateType<T extends FarmerAggregateArgs> = {
      [P in keyof T & keyof AggregateFarmer]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFarmer[P]>
    : Prisma.GetScalarType<T[P], AggregateFarmer[P]>
}




export type FarmerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FarmerWhereInput
  orderBy?: Prisma.FarmerOrderByWithAggregationInput | Prisma.FarmerOrderByWithAggregationInput[]
  by: Prisma.FarmerScalarFieldEnum[] | Prisma.FarmerScalarFieldEnum
  having?: Prisma.FarmerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FarmerCountAggregateInputType | true
  _min?: FarmerMinAggregateInputType
  _max?: FarmerMaxAggregateInputType
}

export type FarmerGroupByOutputType = {
  id: string
  name: string
  locationLatLong: string | null
  languagePref: string
  upiId: string | null
  createdAt: Date
  updatedAt: Date
  _count: FarmerCountAggregateOutputType | null
  _min: FarmerMinAggregateOutputType | null
  _max: FarmerMaxAggregateOutputType | null
}

type GetFarmerGroupByPayload<T extends FarmerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FarmerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FarmerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FarmerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FarmerGroupByOutputType[P]>
      }
    >
  >



export type FarmerWhereInput = {
  AND?: Prisma.FarmerWhereInput | Prisma.FarmerWhereInput[]
  OR?: Prisma.FarmerWhereInput[]
  NOT?: Prisma.FarmerWhereInput | Prisma.FarmerWhereInput[]
  id?: Prisma.StringFilter<"Farmer"> | string
  name?: Prisma.StringFilter<"Farmer"> | string
  locationLatLong?: Prisma.StringNullableFilter<"Farmer"> | string | null
  languagePref?: Prisma.StringFilter<"Farmer"> | string
  upiId?: Prisma.StringNullableFilter<"Farmer"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Farmer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Farmer"> | Date | string
  catalogs?: Prisma.CatalogListRelationFilter
}

export type FarmerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  locationLatLong?: Prisma.SortOrderInput | Prisma.SortOrder
  languagePref?: Prisma.SortOrder
  upiId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  catalogs?: Prisma.CatalogOrderByRelationAggregateInput
}

export type FarmerWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.FarmerWhereInput | Prisma.FarmerWhereInput[]
  OR?: Prisma.FarmerWhereInput[]
  NOT?: Prisma.FarmerWhereInput | Prisma.FarmerWhereInput[]
  name?: Prisma.StringFilter<"Farmer"> | string
  locationLatLong?: Prisma.StringNullableFilter<"Farmer"> | string | null
  languagePref?: Prisma.StringFilter<"Farmer"> | string
  upiId?: Prisma.StringNullableFilter<"Farmer"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Farmer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Farmer"> | Date | string
  catalogs?: Prisma.CatalogListRelationFilter
}, "id">

export type FarmerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  locationLatLong?: Prisma.SortOrderInput | Prisma.SortOrder
  languagePref?: Prisma.SortOrder
  upiId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.FarmerCountOrderByAggregateInput
  _max?: Prisma.FarmerMaxOrderByAggregateInput
  _min?: Prisma.FarmerMinOrderByAggregateInput
}

export type FarmerScalarWhereWithAggregatesInput = {
  AND?: Prisma.FarmerScalarWhereWithAggregatesInput | Prisma.FarmerScalarWhereWithAggregatesInput[]
  OR?: Prisma.FarmerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FarmerScalarWhereWithAggregatesInput | Prisma.FarmerScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Farmer"> | string
  name?: Prisma.StringWithAggregatesFilter<"Farmer"> | string
  locationLatLong?: Prisma.StringNullableWithAggregatesFilter<"Farmer"> | string | null
  languagePref?: Prisma.StringWithAggregatesFilter<"Farmer"> | string
  upiId?: Prisma.StringNullableWithAggregatesFilter<"Farmer"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Farmer"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Farmer"> | Date | string
}

export type FarmerCreateInput = {
  id?: string
  name: string
  locationLatLong?: string | null
  languagePref?: string
  upiId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  catalogs?: Prisma.CatalogCreateNestedManyWithoutFarmerInput
}

export type FarmerUncheckedCreateInput = {
  id?: string
  name: string
  locationLatLong?: string | null
  languagePref?: string
  upiId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  catalogs?: Prisma.CatalogUncheckedCreateNestedManyWithoutFarmerInput
}

export type FarmerUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  locationLatLong?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  languagePref?: Prisma.StringFieldUpdateOperationsInput | string
  upiId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  catalogs?: Prisma.CatalogUpdateManyWithoutFarmerNestedInput
}

export type FarmerUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  locationLatLong?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  languagePref?: Prisma.StringFieldUpdateOperationsInput | string
  upiId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  catalogs?: Prisma.CatalogUncheckedUpdateManyWithoutFarmerNestedInput
}

export type FarmerCreateManyInput = {
  id?: string
  name: string
  locationLatLong?: string | null
  languagePref?: string
  upiId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FarmerUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  locationLatLong?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  languagePref?: Prisma.StringFieldUpdateOperationsInput | string
  upiId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FarmerUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  locationLatLong?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  languagePref?: Prisma.StringFieldUpdateOperationsInput | string
  upiId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FarmerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  locationLatLong?: Prisma.SortOrder
  languagePref?: Prisma.SortOrder
  upiId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FarmerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  locationLatLong?: Prisma.SortOrder
  languagePref?: Prisma.SortOrder
  upiId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FarmerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  locationLatLong?: Prisma.SortOrder
  languagePref?: Prisma.SortOrder
  upiId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FarmerScalarRelationFilter = {
  is?: Prisma.FarmerWhereInput
  isNot?: Prisma.FarmerWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type FarmerCreateNestedOneWithoutCatalogsInput = {
  create?: Prisma.XOR<Prisma.FarmerCreateWithoutCatalogsInput, Prisma.FarmerUncheckedCreateWithoutCatalogsInput>
  connectOrCreate?: Prisma.FarmerCreateOrConnectWithoutCatalogsInput
  connect?: Prisma.FarmerWhereUniqueInput
}

export type FarmerUpdateOneRequiredWithoutCatalogsNestedInput = {
  create?: Prisma.XOR<Prisma.FarmerCreateWithoutCatalogsInput, Prisma.FarmerUncheckedCreateWithoutCatalogsInput>
  connectOrCreate?: Prisma.FarmerCreateOrConnectWithoutCatalogsInput
  upsert?: Prisma.FarmerUpsertWithoutCatalogsInput
  connect?: Prisma.FarmerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FarmerUpdateToOneWithWhereWithoutCatalogsInput, Prisma.FarmerUpdateWithoutCatalogsInput>, Prisma.FarmerUncheckedUpdateWithoutCatalogsInput>
}

export type FarmerCreateWithoutCatalogsInput = {
  id?: string
  name: string
  locationLatLong?: string | null
  languagePref?: string
  upiId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FarmerUncheckedCreateWithoutCatalogsInput = {
  id?: string
  name: string
  locationLatLong?: string | null
  languagePref?: string
  upiId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FarmerCreateOrConnectWithoutCatalogsInput = {
  where: Prisma.FarmerWhereUniqueInput
  create: Prisma.XOR<Prisma.FarmerCreateWithoutCatalogsInput, Prisma.FarmerUncheckedCreateWithoutCatalogsInput>
}

export type FarmerUpsertWithoutCatalogsInput = {
  update: Prisma.XOR<Prisma.FarmerUpdateWithoutCatalogsInput, Prisma.FarmerUncheckedUpdateWithoutCatalogsInput>
  create: Prisma.XOR<Prisma.FarmerCreateWithoutCatalogsInput, Prisma.FarmerUncheckedCreateWithoutCatalogsInput>
  where?: Prisma.FarmerWhereInput
}

export type FarmerUpdateToOneWithWhereWithoutCatalogsInput = {
  where?: Prisma.FarmerWhereInput
  data: Prisma.XOR<Prisma.FarmerUpdateWithoutCatalogsInput, Prisma.FarmerUncheckedUpdateWithoutCatalogsInput>
}

export type FarmerUpdateWithoutCatalogsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  locationLatLong?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  languagePref?: Prisma.StringFieldUpdateOperationsInput | string
  upiId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FarmerUncheckedUpdateWithoutCatalogsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  locationLatLong?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  languagePref?: Prisma.StringFieldUpdateOperationsInput | string
  upiId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type FarmerCountOutputType
 */

export type FarmerCountOutputType = {
  catalogs: number
}

export type FarmerCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  catalogs?: boolean | FarmerCountOutputTypeCountCatalogsArgs
}

/**
 * FarmerCountOutputType without action
 */
export type FarmerCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FarmerCountOutputType
   */
  select?: Prisma.FarmerCountOutputTypeSelect<ExtArgs> | null
}

/**
 * FarmerCountOutputType without action
 */
export type FarmerCountOutputTypeCountCatalogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CatalogWhereInput
}


export type FarmerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  locationLatLong?: boolean
  languagePref?: boolean
  upiId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  catalogs?: boolean | Prisma.Farmer$catalogsArgs<ExtArgs>
  _count?: boolean | Prisma.FarmerCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["farmer"]>

export type FarmerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  locationLatLong?: boolean
  languagePref?: boolean
  upiId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["farmer"]>

export type FarmerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  locationLatLong?: boolean
  languagePref?: boolean
  upiId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["farmer"]>

export type FarmerSelectScalar = {
  id?: boolean
  name?: boolean
  locationLatLong?: boolean
  languagePref?: boolean
  upiId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type FarmerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "locationLatLong" | "languagePref" | "upiId" | "createdAt" | "updatedAt", ExtArgs["result"]["farmer"]>
export type FarmerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  catalogs?: boolean | Prisma.Farmer$catalogsArgs<ExtArgs>
  _count?: boolean | Prisma.FarmerCountOutputTypeDefaultArgs<ExtArgs>
}
export type FarmerIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type FarmerIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $FarmerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Farmer"
  objects: {
    catalogs: Prisma.$CatalogPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    locationLatLong: string | null
    languagePref: string
    upiId: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["farmer"]>
  composites: {}
}

export type FarmerGetPayload<S extends boolean | null | undefined | FarmerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FarmerPayload, S>

export type FarmerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FarmerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FarmerCountAggregateInputType | true
  }

export interface FarmerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Farmer'], meta: { name: 'Farmer' } }
  /**
   * Find zero or one Farmer that matches the filter.
   * @param {FarmerFindUniqueArgs} args - Arguments to find a Farmer
   * @example
   * // Get one Farmer
   * const farmer = await prisma.farmer.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FarmerFindUniqueArgs>(args: Prisma.SelectSubset<T, FarmerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FarmerClient<runtime.Types.Result.GetResult<Prisma.$FarmerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Farmer that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FarmerFindUniqueOrThrowArgs} args - Arguments to find a Farmer
   * @example
   * // Get one Farmer
   * const farmer = await prisma.farmer.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FarmerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FarmerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FarmerClient<runtime.Types.Result.GetResult<Prisma.$FarmerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Farmer that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FarmerFindFirstArgs} args - Arguments to find a Farmer
   * @example
   * // Get one Farmer
   * const farmer = await prisma.farmer.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FarmerFindFirstArgs>(args?: Prisma.SelectSubset<T, FarmerFindFirstArgs<ExtArgs>>): Prisma.Prisma__FarmerClient<runtime.Types.Result.GetResult<Prisma.$FarmerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Farmer that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FarmerFindFirstOrThrowArgs} args - Arguments to find a Farmer
   * @example
   * // Get one Farmer
   * const farmer = await prisma.farmer.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FarmerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FarmerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FarmerClient<runtime.Types.Result.GetResult<Prisma.$FarmerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Farmers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FarmerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Farmers
   * const farmers = await prisma.farmer.findMany()
   * 
   * // Get first 10 Farmers
   * const farmers = await prisma.farmer.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const farmerWithIdOnly = await prisma.farmer.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FarmerFindManyArgs>(args?: Prisma.SelectSubset<T, FarmerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FarmerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Farmer.
   * @param {FarmerCreateArgs} args - Arguments to create a Farmer.
   * @example
   * // Create one Farmer
   * const Farmer = await prisma.farmer.create({
   *   data: {
   *     // ... data to create a Farmer
   *   }
   * })
   * 
   */
  create<T extends FarmerCreateArgs>(args: Prisma.SelectSubset<T, FarmerCreateArgs<ExtArgs>>): Prisma.Prisma__FarmerClient<runtime.Types.Result.GetResult<Prisma.$FarmerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Farmers.
   * @param {FarmerCreateManyArgs} args - Arguments to create many Farmers.
   * @example
   * // Create many Farmers
   * const farmer = await prisma.farmer.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FarmerCreateManyArgs>(args?: Prisma.SelectSubset<T, FarmerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Farmers and returns the data saved in the database.
   * @param {FarmerCreateManyAndReturnArgs} args - Arguments to create many Farmers.
   * @example
   * // Create many Farmers
   * const farmer = await prisma.farmer.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Farmers and only return the `id`
   * const farmerWithIdOnly = await prisma.farmer.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FarmerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FarmerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FarmerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Farmer.
   * @param {FarmerDeleteArgs} args - Arguments to delete one Farmer.
   * @example
   * // Delete one Farmer
   * const Farmer = await prisma.farmer.delete({
   *   where: {
   *     // ... filter to delete one Farmer
   *   }
   * })
   * 
   */
  delete<T extends FarmerDeleteArgs>(args: Prisma.SelectSubset<T, FarmerDeleteArgs<ExtArgs>>): Prisma.Prisma__FarmerClient<runtime.Types.Result.GetResult<Prisma.$FarmerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Farmer.
   * @param {FarmerUpdateArgs} args - Arguments to update one Farmer.
   * @example
   * // Update one Farmer
   * const farmer = await prisma.farmer.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FarmerUpdateArgs>(args: Prisma.SelectSubset<T, FarmerUpdateArgs<ExtArgs>>): Prisma.Prisma__FarmerClient<runtime.Types.Result.GetResult<Prisma.$FarmerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Farmers.
   * @param {FarmerDeleteManyArgs} args - Arguments to filter Farmers to delete.
   * @example
   * // Delete a few Farmers
   * const { count } = await prisma.farmer.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FarmerDeleteManyArgs>(args?: Prisma.SelectSubset<T, FarmerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Farmers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FarmerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Farmers
   * const farmer = await prisma.farmer.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FarmerUpdateManyArgs>(args: Prisma.SelectSubset<T, FarmerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Farmers and returns the data updated in the database.
   * @param {FarmerUpdateManyAndReturnArgs} args - Arguments to update many Farmers.
   * @example
   * // Update many Farmers
   * const farmer = await prisma.farmer.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Farmers and only return the `id`
   * const farmerWithIdOnly = await prisma.farmer.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FarmerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FarmerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FarmerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Farmer.
   * @param {FarmerUpsertArgs} args - Arguments to update or create a Farmer.
   * @example
   * // Update or create a Farmer
   * const farmer = await prisma.farmer.upsert({
   *   create: {
   *     // ... data to create a Farmer
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Farmer we want to update
   *   }
   * })
   */
  upsert<T extends FarmerUpsertArgs>(args: Prisma.SelectSubset<T, FarmerUpsertArgs<ExtArgs>>): Prisma.Prisma__FarmerClient<runtime.Types.Result.GetResult<Prisma.$FarmerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Farmers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FarmerCountArgs} args - Arguments to filter Farmers to count.
   * @example
   * // Count the number of Farmers
   * const count = await prisma.farmer.count({
   *   where: {
   *     // ... the filter for the Farmers we want to count
   *   }
   * })
  **/
  count<T extends FarmerCountArgs>(
    args?: Prisma.Subset<T, FarmerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FarmerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Farmer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FarmerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FarmerAggregateArgs>(args: Prisma.Subset<T, FarmerAggregateArgs>): Prisma.PrismaPromise<GetFarmerAggregateType<T>>

  /**
   * Group by Farmer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FarmerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FarmerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FarmerGroupByArgs['orderBy'] }
      : { orderBy?: FarmerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FarmerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFarmerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Farmer model
 */
readonly fields: FarmerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Farmer.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FarmerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  catalogs<T extends Prisma.Farmer$catalogsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Farmer$catalogsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CatalogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Farmer model
 */
export interface FarmerFieldRefs {
  readonly id: Prisma.FieldRef<"Farmer", 'String'>
  readonly name: Prisma.FieldRef<"Farmer", 'String'>
  readonly locationLatLong: Prisma.FieldRef<"Farmer", 'String'>
  readonly languagePref: Prisma.FieldRef<"Farmer", 'String'>
  readonly upiId: Prisma.FieldRef<"Farmer", 'String'>
  readonly createdAt: Prisma.FieldRef<"Farmer", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Farmer", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Farmer findUnique
 */
export type FarmerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Farmer
   */
  select?: Prisma.FarmerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Farmer
   */
  omit?: Prisma.FarmerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FarmerInclude<ExtArgs> | null
  /**
   * Filter, which Farmer to fetch.
   */
  where: Prisma.FarmerWhereUniqueInput
}

/**
 * Farmer findUniqueOrThrow
 */
export type FarmerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Farmer
   */
  select?: Prisma.FarmerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Farmer
   */
  omit?: Prisma.FarmerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FarmerInclude<ExtArgs> | null
  /**
   * Filter, which Farmer to fetch.
   */
  where: Prisma.FarmerWhereUniqueInput
}

/**
 * Farmer findFirst
 */
export type FarmerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Farmer
   */
  select?: Prisma.FarmerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Farmer
   */
  omit?: Prisma.FarmerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FarmerInclude<ExtArgs> | null
  /**
   * Filter, which Farmer to fetch.
   */
  where?: Prisma.FarmerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Farmers to fetch.
   */
  orderBy?: Prisma.FarmerOrderByWithRelationInput | Prisma.FarmerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Farmers.
   */
  cursor?: Prisma.FarmerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Farmers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Farmers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Farmers.
   */
  distinct?: Prisma.FarmerScalarFieldEnum | Prisma.FarmerScalarFieldEnum[]
}

/**
 * Farmer findFirstOrThrow
 */
export type FarmerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Farmer
   */
  select?: Prisma.FarmerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Farmer
   */
  omit?: Prisma.FarmerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FarmerInclude<ExtArgs> | null
  /**
   * Filter, which Farmer to fetch.
   */
  where?: Prisma.FarmerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Farmers to fetch.
   */
  orderBy?: Prisma.FarmerOrderByWithRelationInput | Prisma.FarmerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Farmers.
   */
  cursor?: Prisma.FarmerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Farmers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Farmers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Farmers.
   */
  distinct?: Prisma.FarmerScalarFieldEnum | Prisma.FarmerScalarFieldEnum[]
}

/**
 * Farmer findMany
 */
export type FarmerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Farmer
   */
  select?: Prisma.FarmerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Farmer
   */
  omit?: Prisma.FarmerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FarmerInclude<ExtArgs> | null
  /**
   * Filter, which Farmers to fetch.
   */
  where?: Prisma.FarmerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Farmers to fetch.
   */
  orderBy?: Prisma.FarmerOrderByWithRelationInput | Prisma.FarmerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Farmers.
   */
  cursor?: Prisma.FarmerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Farmers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Farmers.
   */
  skip?: number
  distinct?: Prisma.FarmerScalarFieldEnum | Prisma.FarmerScalarFieldEnum[]
}

/**
 * Farmer create
 */
export type FarmerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Farmer
   */
  select?: Prisma.FarmerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Farmer
   */
  omit?: Prisma.FarmerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FarmerInclude<ExtArgs> | null
  /**
   * The data needed to create a Farmer.
   */
  data: Prisma.XOR<Prisma.FarmerCreateInput, Prisma.FarmerUncheckedCreateInput>
}

/**
 * Farmer createMany
 */
export type FarmerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Farmers.
   */
  data: Prisma.FarmerCreateManyInput | Prisma.FarmerCreateManyInput[]
}

/**
 * Farmer createManyAndReturn
 */
export type FarmerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Farmer
   */
  select?: Prisma.FarmerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Farmer
   */
  omit?: Prisma.FarmerOmit<ExtArgs> | null
  /**
   * The data used to create many Farmers.
   */
  data: Prisma.FarmerCreateManyInput | Prisma.FarmerCreateManyInput[]
}

/**
 * Farmer update
 */
export type FarmerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Farmer
   */
  select?: Prisma.FarmerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Farmer
   */
  omit?: Prisma.FarmerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FarmerInclude<ExtArgs> | null
  /**
   * The data needed to update a Farmer.
   */
  data: Prisma.XOR<Prisma.FarmerUpdateInput, Prisma.FarmerUncheckedUpdateInput>
  /**
   * Choose, which Farmer to update.
   */
  where: Prisma.FarmerWhereUniqueInput
}

/**
 * Farmer updateMany
 */
export type FarmerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Farmers.
   */
  data: Prisma.XOR<Prisma.FarmerUpdateManyMutationInput, Prisma.FarmerUncheckedUpdateManyInput>
  /**
   * Filter which Farmers to update
   */
  where?: Prisma.FarmerWhereInput
  /**
   * Limit how many Farmers to update.
   */
  limit?: number
}

/**
 * Farmer updateManyAndReturn
 */
export type FarmerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Farmer
   */
  select?: Prisma.FarmerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Farmer
   */
  omit?: Prisma.FarmerOmit<ExtArgs> | null
  /**
   * The data used to update Farmers.
   */
  data: Prisma.XOR<Prisma.FarmerUpdateManyMutationInput, Prisma.FarmerUncheckedUpdateManyInput>
  /**
   * Filter which Farmers to update
   */
  where?: Prisma.FarmerWhereInput
  /**
   * Limit how many Farmers to update.
   */
  limit?: number
}

/**
 * Farmer upsert
 */
export type FarmerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Farmer
   */
  select?: Prisma.FarmerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Farmer
   */
  omit?: Prisma.FarmerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FarmerInclude<ExtArgs> | null
  /**
   * The filter to search for the Farmer to update in case it exists.
   */
  where: Prisma.FarmerWhereUniqueInput
  /**
   * In case the Farmer found by the `where` argument doesn't exist, create a new Farmer with this data.
   */
  create: Prisma.XOR<Prisma.FarmerCreateInput, Prisma.FarmerUncheckedCreateInput>
  /**
   * In case the Farmer was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FarmerUpdateInput, Prisma.FarmerUncheckedUpdateInput>
}

/**
 * Farmer delete
 */
export type FarmerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Farmer
   */
  select?: Prisma.FarmerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Farmer
   */
  omit?: Prisma.FarmerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FarmerInclude<ExtArgs> | null
  /**
   * Filter which Farmer to delete.
   */
  where: Prisma.FarmerWhereUniqueInput
}

/**
 * Farmer deleteMany
 */
export type FarmerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Farmers to delete
   */
  where?: Prisma.FarmerWhereInput
  /**
   * Limit how many Farmers to delete.
   */
  limit?: number
}

/**
 * Farmer.catalogs
 */
export type Farmer$catalogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Catalog
   */
  select?: Prisma.CatalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Catalog
   */
  omit?: Prisma.CatalogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatalogInclude<ExtArgs> | null
  where?: Prisma.CatalogWhereInput
  orderBy?: Prisma.CatalogOrderByWithRelationInput | Prisma.CatalogOrderByWithRelationInput[]
  cursor?: Prisma.CatalogWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CatalogScalarFieldEnum | Prisma.CatalogScalarFieldEnum[]
}

/**
 * Farmer without action
 */
export type FarmerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Farmer
   */
  select?: Prisma.FarmerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Farmer
   */
  omit?: Prisma.FarmerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FarmerInclude<ExtArgs> | null
}
