
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `NetworkLog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model NetworkLog
 * 
 */
export type NetworkLogModel = runtime.Types.Result.DefaultSelection<Prisma.$NetworkLogPayload>

export type AggregateNetworkLog = {
  _count: NetworkLogCountAggregateOutputType | null
  _min: NetworkLogMinAggregateOutputType | null
  _max: NetworkLogMaxAggregateOutputType | null
}

export type NetworkLogMinAggregateOutputType = {
  id: string | null
  type: $Enums.NetworkLogType | null
  timestamp: Date | null
}

export type NetworkLogMaxAggregateOutputType = {
  id: string | null
  type: $Enums.NetworkLogType | null
  timestamp: Date | null
}

export type NetworkLogCountAggregateOutputType = {
  id: number
  type: number
  payload: number
  timestamp: number
  _all: number
}


export type NetworkLogMinAggregateInputType = {
  id?: true
  type?: true
  timestamp?: true
}

export type NetworkLogMaxAggregateInputType = {
  id?: true
  type?: true
  timestamp?: true
}

export type NetworkLogCountAggregateInputType = {
  id?: true
  type?: true
  payload?: true
  timestamp?: true
  _all?: true
}

export type NetworkLogAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NetworkLog to aggregate.
   */
  where?: Prisma.NetworkLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NetworkLogs to fetch.
   */
  orderBy?: Prisma.NetworkLogOrderByWithRelationInput | Prisma.NetworkLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.NetworkLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NetworkLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NetworkLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned NetworkLogs
  **/
  _count?: true | NetworkLogCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: NetworkLogMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: NetworkLogMaxAggregateInputType
}

export type GetNetworkLogAggregateType<T extends NetworkLogAggregateArgs> = {
      [P in keyof T & keyof AggregateNetworkLog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateNetworkLog[P]>
    : Prisma.GetScalarType<T[P], AggregateNetworkLog[P]>
}




export type NetworkLogGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NetworkLogWhereInput
  orderBy?: Prisma.NetworkLogOrderByWithAggregationInput | Prisma.NetworkLogOrderByWithAggregationInput[]
  by: Prisma.NetworkLogScalarFieldEnum[] | Prisma.NetworkLogScalarFieldEnum
  having?: Prisma.NetworkLogScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: NetworkLogCountAggregateInputType | true
  _min?: NetworkLogMinAggregateInputType
  _max?: NetworkLogMaxAggregateInputType
}

export type NetworkLogGroupByOutputType = {
  id: string
  type: $Enums.NetworkLogType
  payload: runtime.JsonValue
  timestamp: Date
  _count: NetworkLogCountAggregateOutputType | null
  _min: NetworkLogMinAggregateOutputType | null
  _max: NetworkLogMaxAggregateOutputType | null
}

type GetNetworkLogGroupByPayload<T extends NetworkLogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<NetworkLogGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof NetworkLogGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], NetworkLogGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], NetworkLogGroupByOutputType[P]>
      }
    >
  >



export type NetworkLogWhereInput = {
  AND?: Prisma.NetworkLogWhereInput | Prisma.NetworkLogWhereInput[]
  OR?: Prisma.NetworkLogWhereInput[]
  NOT?: Prisma.NetworkLogWhereInput | Prisma.NetworkLogWhereInput[]
  id?: Prisma.StringFilter<"NetworkLog"> | string
  type?: Prisma.EnumNetworkLogTypeFilter<"NetworkLog"> | $Enums.NetworkLogType
  payload?: Prisma.JsonFilter<"NetworkLog">
  timestamp?: Prisma.DateTimeFilter<"NetworkLog"> | Date | string
}

export type NetworkLogOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  payload?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
}

export type NetworkLogWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.NetworkLogWhereInput | Prisma.NetworkLogWhereInput[]
  OR?: Prisma.NetworkLogWhereInput[]
  NOT?: Prisma.NetworkLogWhereInput | Prisma.NetworkLogWhereInput[]
  type?: Prisma.EnumNetworkLogTypeFilter<"NetworkLog"> | $Enums.NetworkLogType
  payload?: Prisma.JsonFilter<"NetworkLog">
  timestamp?: Prisma.DateTimeFilter<"NetworkLog"> | Date | string
}, "id">

export type NetworkLogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  payload?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  _count?: Prisma.NetworkLogCountOrderByAggregateInput
  _max?: Prisma.NetworkLogMaxOrderByAggregateInput
  _min?: Prisma.NetworkLogMinOrderByAggregateInput
}

export type NetworkLogScalarWhereWithAggregatesInput = {
  AND?: Prisma.NetworkLogScalarWhereWithAggregatesInput | Prisma.NetworkLogScalarWhereWithAggregatesInput[]
  OR?: Prisma.NetworkLogScalarWhereWithAggregatesInput[]
  NOT?: Prisma.NetworkLogScalarWhereWithAggregatesInput | Prisma.NetworkLogScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"NetworkLog"> | string
  type?: Prisma.EnumNetworkLogTypeWithAggregatesFilter<"NetworkLog"> | $Enums.NetworkLogType
  payload?: Prisma.JsonWithAggregatesFilter<"NetworkLog">
  timestamp?: Prisma.DateTimeWithAggregatesFilter<"NetworkLog"> | Date | string
}

export type NetworkLogCreateInput = {
  id?: string
  type: $Enums.NetworkLogType
  payload: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timestamp?: Date | string
}

export type NetworkLogUncheckedCreateInput = {
  id?: string
  type: $Enums.NetworkLogType
  payload: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timestamp?: Date | string
}

export type NetworkLogUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumNetworkLogTypeFieldUpdateOperationsInput | $Enums.NetworkLogType
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NetworkLogUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumNetworkLogTypeFieldUpdateOperationsInput | $Enums.NetworkLogType
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NetworkLogCreateManyInput = {
  id?: string
  type: $Enums.NetworkLogType
  payload: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timestamp?: Date | string
}

export type NetworkLogUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumNetworkLogTypeFieldUpdateOperationsInput | $Enums.NetworkLogType
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NetworkLogUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumNetworkLogTypeFieldUpdateOperationsInput | $Enums.NetworkLogType
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NetworkLogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  payload?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
}

export type NetworkLogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
}

export type NetworkLogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
}

export type EnumNetworkLogTypeFieldUpdateOperationsInput = {
  set?: $Enums.NetworkLogType
}



export type NetworkLogSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  payload?: boolean
  timestamp?: boolean
}, ExtArgs["result"]["networkLog"]>

export type NetworkLogSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  payload?: boolean
  timestamp?: boolean
}, ExtArgs["result"]["networkLog"]>

export type NetworkLogSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  payload?: boolean
  timestamp?: boolean
}, ExtArgs["result"]["networkLog"]>

export type NetworkLogSelectScalar = {
  id?: boolean
  type?: boolean
  payload?: boolean
  timestamp?: boolean
}

export type NetworkLogOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "type" | "payload" | "timestamp", ExtArgs["result"]["networkLog"]>

export type $NetworkLogPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "NetworkLog"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    type: $Enums.NetworkLogType
    payload: runtime.JsonValue
    timestamp: Date
  }, ExtArgs["result"]["networkLog"]>
  composites: {}
}

export type NetworkLogGetPayload<S extends boolean | null | undefined | NetworkLogDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$NetworkLogPayload, S>

export type NetworkLogCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<NetworkLogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: NetworkLogCountAggregateInputType | true
  }

export interface NetworkLogDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['NetworkLog'], meta: { name: 'NetworkLog' } }
  /**
   * Find zero or one NetworkLog that matches the filter.
   * @param {NetworkLogFindUniqueArgs} args - Arguments to find a NetworkLog
   * @example
   * // Get one NetworkLog
   * const networkLog = await prisma.networkLog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends NetworkLogFindUniqueArgs>(args: Prisma.SelectSubset<T, NetworkLogFindUniqueArgs<ExtArgs>>): Prisma.Prisma__NetworkLogClient<runtime.Types.Result.GetResult<Prisma.$NetworkLogPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one NetworkLog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {NetworkLogFindUniqueOrThrowArgs} args - Arguments to find a NetworkLog
   * @example
   * // Get one NetworkLog
   * const networkLog = await prisma.networkLog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends NetworkLogFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, NetworkLogFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__NetworkLogClient<runtime.Types.Result.GetResult<Prisma.$NetworkLogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NetworkLog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NetworkLogFindFirstArgs} args - Arguments to find a NetworkLog
   * @example
   * // Get one NetworkLog
   * const networkLog = await prisma.networkLog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends NetworkLogFindFirstArgs>(args?: Prisma.SelectSubset<T, NetworkLogFindFirstArgs<ExtArgs>>): Prisma.Prisma__NetworkLogClient<runtime.Types.Result.GetResult<Prisma.$NetworkLogPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NetworkLog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NetworkLogFindFirstOrThrowArgs} args - Arguments to find a NetworkLog
   * @example
   * // Get one NetworkLog
   * const networkLog = await prisma.networkLog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends NetworkLogFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, NetworkLogFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__NetworkLogClient<runtime.Types.Result.GetResult<Prisma.$NetworkLogPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more NetworkLogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NetworkLogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all NetworkLogs
   * const networkLogs = await prisma.networkLog.findMany()
   * 
   * // Get first 10 NetworkLogs
   * const networkLogs = await prisma.networkLog.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const networkLogWithIdOnly = await prisma.networkLog.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends NetworkLogFindManyArgs>(args?: Prisma.SelectSubset<T, NetworkLogFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NetworkLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a NetworkLog.
   * @param {NetworkLogCreateArgs} args - Arguments to create a NetworkLog.
   * @example
   * // Create one NetworkLog
   * const NetworkLog = await prisma.networkLog.create({
   *   data: {
   *     // ... data to create a NetworkLog
   *   }
   * })
   * 
   */
  create<T extends NetworkLogCreateArgs>(args: Prisma.SelectSubset<T, NetworkLogCreateArgs<ExtArgs>>): Prisma.Prisma__NetworkLogClient<runtime.Types.Result.GetResult<Prisma.$NetworkLogPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many NetworkLogs.
   * @param {NetworkLogCreateManyArgs} args - Arguments to create many NetworkLogs.
   * @example
   * // Create many NetworkLogs
   * const networkLog = await prisma.networkLog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends NetworkLogCreateManyArgs>(args?: Prisma.SelectSubset<T, NetworkLogCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many NetworkLogs and returns the data saved in the database.
   * @param {NetworkLogCreateManyAndReturnArgs} args - Arguments to create many NetworkLogs.
   * @example
   * // Create many NetworkLogs
   * const networkLog = await prisma.networkLog.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many NetworkLogs and only return the `id`
   * const networkLogWithIdOnly = await prisma.networkLog.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends NetworkLogCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, NetworkLogCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NetworkLogPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a NetworkLog.
   * @param {NetworkLogDeleteArgs} args - Arguments to delete one NetworkLog.
   * @example
   * // Delete one NetworkLog
   * const NetworkLog = await prisma.networkLog.delete({
   *   where: {
   *     // ... filter to delete one NetworkLog
   *   }
   * })
   * 
   */
  delete<T extends NetworkLogDeleteArgs>(args: Prisma.SelectSubset<T, NetworkLogDeleteArgs<ExtArgs>>): Prisma.Prisma__NetworkLogClient<runtime.Types.Result.GetResult<Prisma.$NetworkLogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one NetworkLog.
   * @param {NetworkLogUpdateArgs} args - Arguments to update one NetworkLog.
   * @example
   * // Update one NetworkLog
   * const networkLog = await prisma.networkLog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends NetworkLogUpdateArgs>(args: Prisma.SelectSubset<T, NetworkLogUpdateArgs<ExtArgs>>): Prisma.Prisma__NetworkLogClient<runtime.Types.Result.GetResult<Prisma.$NetworkLogPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more NetworkLogs.
   * @param {NetworkLogDeleteManyArgs} args - Arguments to filter NetworkLogs to delete.
   * @example
   * // Delete a few NetworkLogs
   * const { count } = await prisma.networkLog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends NetworkLogDeleteManyArgs>(args?: Prisma.SelectSubset<T, NetworkLogDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NetworkLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NetworkLogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many NetworkLogs
   * const networkLog = await prisma.networkLog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends NetworkLogUpdateManyArgs>(args: Prisma.SelectSubset<T, NetworkLogUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NetworkLogs and returns the data updated in the database.
   * @param {NetworkLogUpdateManyAndReturnArgs} args - Arguments to update many NetworkLogs.
   * @example
   * // Update many NetworkLogs
   * const networkLog = await prisma.networkLog.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more NetworkLogs and only return the `id`
   * const networkLogWithIdOnly = await prisma.networkLog.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends NetworkLogUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, NetworkLogUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NetworkLogPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one NetworkLog.
   * @param {NetworkLogUpsertArgs} args - Arguments to update or create a NetworkLog.
   * @example
   * // Update or create a NetworkLog
   * const networkLog = await prisma.networkLog.upsert({
   *   create: {
   *     // ... data to create a NetworkLog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the NetworkLog we want to update
   *   }
   * })
   */
  upsert<T extends NetworkLogUpsertArgs>(args: Prisma.SelectSubset<T, NetworkLogUpsertArgs<ExtArgs>>): Prisma.Prisma__NetworkLogClient<runtime.Types.Result.GetResult<Prisma.$NetworkLogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of NetworkLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NetworkLogCountArgs} args - Arguments to filter NetworkLogs to count.
   * @example
   * // Count the number of NetworkLogs
   * const count = await prisma.networkLog.count({
   *   where: {
   *     // ... the filter for the NetworkLogs we want to count
   *   }
   * })
  **/
  count<T extends NetworkLogCountArgs>(
    args?: Prisma.Subset<T, NetworkLogCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], NetworkLogCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a NetworkLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NetworkLogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends NetworkLogAggregateArgs>(args: Prisma.Subset<T, NetworkLogAggregateArgs>): Prisma.PrismaPromise<GetNetworkLogAggregateType<T>>

  /**
   * Group by NetworkLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NetworkLogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends NetworkLogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: NetworkLogGroupByArgs['orderBy'] }
      : { orderBy?: NetworkLogGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, NetworkLogGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetNetworkLogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the NetworkLog model
 */
readonly fields: NetworkLogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for NetworkLog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__NetworkLogClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the NetworkLog model
 */
export interface NetworkLogFieldRefs {
  readonly id: Prisma.FieldRef<"NetworkLog", 'String'>
  readonly type: Prisma.FieldRef<"NetworkLog", 'NetworkLogType'>
  readonly payload: Prisma.FieldRef<"NetworkLog", 'Json'>
  readonly timestamp: Prisma.FieldRef<"NetworkLog", 'DateTime'>
}
    

// Custom InputTypes
/**
 * NetworkLog findUnique
 */
export type NetworkLogFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NetworkLog
   */
  select?: Prisma.NetworkLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NetworkLog
   */
  omit?: Prisma.NetworkLogOmit<ExtArgs> | null
  /**
   * Filter, which NetworkLog to fetch.
   */
  where: Prisma.NetworkLogWhereUniqueInput
}

/**
 * NetworkLog findUniqueOrThrow
 */
export type NetworkLogFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NetworkLog
   */
  select?: Prisma.NetworkLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NetworkLog
   */
  omit?: Prisma.NetworkLogOmit<ExtArgs> | null
  /**
   * Filter, which NetworkLog to fetch.
   */
  where: Prisma.NetworkLogWhereUniqueInput
}

/**
 * NetworkLog findFirst
 */
export type NetworkLogFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NetworkLog
   */
  select?: Prisma.NetworkLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NetworkLog
   */
  omit?: Prisma.NetworkLogOmit<ExtArgs> | null
  /**
   * Filter, which NetworkLog to fetch.
   */
  where?: Prisma.NetworkLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NetworkLogs to fetch.
   */
  orderBy?: Prisma.NetworkLogOrderByWithRelationInput | Prisma.NetworkLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NetworkLogs.
   */
  cursor?: Prisma.NetworkLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NetworkLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NetworkLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NetworkLogs.
   */
  distinct?: Prisma.NetworkLogScalarFieldEnum | Prisma.NetworkLogScalarFieldEnum[]
}

/**
 * NetworkLog findFirstOrThrow
 */
export type NetworkLogFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NetworkLog
   */
  select?: Prisma.NetworkLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NetworkLog
   */
  omit?: Prisma.NetworkLogOmit<ExtArgs> | null
  /**
   * Filter, which NetworkLog to fetch.
   */
  where?: Prisma.NetworkLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NetworkLogs to fetch.
   */
  orderBy?: Prisma.NetworkLogOrderByWithRelationInput | Prisma.NetworkLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NetworkLogs.
   */
  cursor?: Prisma.NetworkLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NetworkLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NetworkLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NetworkLogs.
   */
  distinct?: Prisma.NetworkLogScalarFieldEnum | Prisma.NetworkLogScalarFieldEnum[]
}

/**
 * NetworkLog findMany
 */
export type NetworkLogFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NetworkLog
   */
  select?: Prisma.NetworkLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NetworkLog
   */
  omit?: Prisma.NetworkLogOmit<ExtArgs> | null
  /**
   * Filter, which NetworkLogs to fetch.
   */
  where?: Prisma.NetworkLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NetworkLogs to fetch.
   */
  orderBy?: Prisma.NetworkLogOrderByWithRelationInput | Prisma.NetworkLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing NetworkLogs.
   */
  cursor?: Prisma.NetworkLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NetworkLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NetworkLogs.
   */
  skip?: number
  distinct?: Prisma.NetworkLogScalarFieldEnum | Prisma.NetworkLogScalarFieldEnum[]
}

/**
 * NetworkLog create
 */
export type NetworkLogCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NetworkLog
   */
  select?: Prisma.NetworkLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NetworkLog
   */
  omit?: Prisma.NetworkLogOmit<ExtArgs> | null
  /**
   * The data needed to create a NetworkLog.
   */
  data: Prisma.XOR<Prisma.NetworkLogCreateInput, Prisma.NetworkLogUncheckedCreateInput>
}

/**
 * NetworkLog createMany
 */
export type NetworkLogCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many NetworkLogs.
   */
  data: Prisma.NetworkLogCreateManyInput | Prisma.NetworkLogCreateManyInput[]
}

/**
 * NetworkLog createManyAndReturn
 */
export type NetworkLogCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NetworkLog
   */
  select?: Prisma.NetworkLogSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NetworkLog
   */
  omit?: Prisma.NetworkLogOmit<ExtArgs> | null
  /**
   * The data used to create many NetworkLogs.
   */
  data: Prisma.NetworkLogCreateManyInput | Prisma.NetworkLogCreateManyInput[]
}

/**
 * NetworkLog update
 */
export type NetworkLogUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NetworkLog
   */
  select?: Prisma.NetworkLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NetworkLog
   */
  omit?: Prisma.NetworkLogOmit<ExtArgs> | null
  /**
   * The data needed to update a NetworkLog.
   */
  data: Prisma.XOR<Prisma.NetworkLogUpdateInput, Prisma.NetworkLogUncheckedUpdateInput>
  /**
   * Choose, which NetworkLog to update.
   */
  where: Prisma.NetworkLogWhereUniqueInput
}

/**
 * NetworkLog updateMany
 */
export type NetworkLogUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update NetworkLogs.
   */
  data: Prisma.XOR<Prisma.NetworkLogUpdateManyMutationInput, Prisma.NetworkLogUncheckedUpdateManyInput>
  /**
   * Filter which NetworkLogs to update
   */
  where?: Prisma.NetworkLogWhereInput
  /**
   * Limit how many NetworkLogs to update.
   */
  limit?: number
}

/**
 * NetworkLog updateManyAndReturn
 */
export type NetworkLogUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NetworkLog
   */
  select?: Prisma.NetworkLogSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NetworkLog
   */
  omit?: Prisma.NetworkLogOmit<ExtArgs> | null
  /**
   * The data used to update NetworkLogs.
   */
  data: Prisma.XOR<Prisma.NetworkLogUpdateManyMutationInput, Prisma.NetworkLogUncheckedUpdateManyInput>
  /**
   * Filter which NetworkLogs to update
   */
  where?: Prisma.NetworkLogWhereInput
  /**
   * Limit how many NetworkLogs to update.
   */
  limit?: number
}

/**
 * NetworkLog upsert
 */
export type NetworkLogUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NetworkLog
   */
  select?: Prisma.NetworkLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NetworkLog
   */
  omit?: Prisma.NetworkLogOmit<ExtArgs> | null
  /**
   * The filter to search for the NetworkLog to update in case it exists.
   */
  where: Prisma.NetworkLogWhereUniqueInput
  /**
   * In case the NetworkLog found by the `where` argument doesn't exist, create a new NetworkLog with this data.
   */
  create: Prisma.XOR<Prisma.NetworkLogCreateInput, Prisma.NetworkLogUncheckedCreateInput>
  /**
   * In case the NetworkLog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.NetworkLogUpdateInput, Prisma.NetworkLogUncheckedUpdateInput>
}

/**
 * NetworkLog delete
 */
export type NetworkLogDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NetworkLog
   */
  select?: Prisma.NetworkLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NetworkLog
   */
  omit?: Prisma.NetworkLogOmit<ExtArgs> | null
  /**
   * Filter which NetworkLog to delete.
   */
  where: Prisma.NetworkLogWhereUniqueInput
}

/**
 * NetworkLog deleteMany
 */
export type NetworkLogDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NetworkLogs to delete
   */
  where?: Prisma.NetworkLogWhereInput
  /**
   * Limit how many NetworkLogs to delete.
   */
  limit?: number
}

/**
 * NetworkLog without action
 */
export type NetworkLogDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NetworkLog
   */
  select?: Prisma.NetworkLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NetworkLog
   */
  omit?: Prisma.NetworkLogOmit<ExtArgs> | null
}
